#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_placement      exterior
yabai -m config window_border_width          5
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost on
# yabai -m config active_window_border_color   0xff4CB8D6
yabai -m config active_window_border_color   0xffa9b665
yabai -m config normal_window_border_color   0xff928374
yabai -m config insert_window_border_color   0xff45707a
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  16
yabai -m config bottom_padding               16
yabai -m config left_padding                 16
yabai -m config right_padding                16
yabai -m config window_gap                   16
yabai -m config external_bar                 "main:26:0"

# kill any existing limelight process if one exists, before we launch a new one
# killall limelight &> /dev/null
# limelight &> /dev/null &

echo "yabai configuration loaded.."

